# Generated by Django 3.0 on 2021-04-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='cart_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plasticproduct',
            name='pproduct_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recycleproduct',
            name='rproduct_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
