# Generated by Django 3.0 on 2021-02-27 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.BigIntegerField()),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('checksum', models.CharField(blank=True, max_length=100, null=True)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ep.Master')),
            ],
        ),
        migrations.CreateModel(
            name='AcceptRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_quantity', models.BigIntegerField(default=1)),
                ('request_date', models.DateTimeField()),
                ('accept_date', models.DateTimeField()),
                ('plasticcollector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep.PlasticC')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep.RequestButton')),
            ],
        ),
    ]
