# Generated by Django 3.1 on 2021-04-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='order_comment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
