# Generated by Django 3.0 on 2021-03-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep', '0002_auto_20210312_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comp_postalcode',
            field=models.BigIntegerField(),
        ),
    ]
