# Generated by Django 2.0 on 2021-03-04 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep', '0002_auto_20210304_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_total', models.BigIntegerField(default=0)),
                ('payment_status', models.CharField(default='', max_length=20)),
                ('customer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ep.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='cart_id',
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
