# Generated by Django 2.0 on 2021-02-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep', '0002_addtocart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='cart_quantity',
            field=models.BigIntegerField(default=1),
        ),
    ]
