# Generated by Django 3.0 on 2021-04-15 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep', '0002_auto_20210415_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasticrequest',
            name='transaction_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ep.Transaction'),
        ),
    ]
