# Generated by Django 2.0 on 2021-01-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep', '0002_auto_20210128_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasticc',
            name='owner_contact',
            field=models.BigIntegerField(blank=True),
        ),
    ]
