# Generated by Django 3.0 on 2021-04-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep', '0003_plasticrequest_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasticrequest',
            name='payment_status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='plasticrequest',
            name='total_price',
            field=models.BigIntegerField(default=0),
        ),
    ]
