# Generated by Django 3.0 on 2021-03-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep', '0003_auto_20210312_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='postalcode',
            field=models.BigIntegerField(null=True),
        ),
    ]
