# Generated by Django 3.0 on 2021-02-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ep', '0003_auto_20210227_1717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcceptRequest',
        ),
    ]
