# Generated by Django 2.0 on 2021-01-28 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep', '0004_auto_20210128_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlasticProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pproduct_name', models.CharField(max_length=100)),
                ('pproduct_date', models.DateTimeField()),
                ('pproduct_price', models.BigIntegerField(default=0)),
                ('pproduct_image', models.ImageField(upload_to='pproductimg/')),
                ('pproduct_quantity', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='plasticc',
            name='owner_contact',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plasticproduct',
            name='plasticc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep.PlasticC'),
        ),
    ]
