# Generated by Django 2.0 on 2021-03-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep', '0004_auto_20210304_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='postalcode',
            field=models.BigIntegerField(),
        ),
    ]
