# Generated by Django 3.0 on 2021-03-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ep', '0004_auto_20210327_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_total',
        ),
    ]
