# Generated by Django 3.0 on 2021-02-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep', '0004_delete_acceptrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasticrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
