# Generated by Django 2.0 on 2021-01-30 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep', '0005_auto_20210128_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField()),
                ('request_quantity', models.BigIntegerField(default=0)),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep.Company')),
                ('plasticc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep.PlasticC')),
                ('pproduct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep.PlasticProduct')),
            ],
        ),
    ]
