# Generated by Django 2.0 on 2021-02-02 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep', '0006_requestbutton'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rproduct_name', models.CharField(max_length=100)),
                ('rproduct_date', models.DateTimeField()),
                ('rproduct_price', models.BigIntegerField(default=0)),
                ('rproduct_image', models.ImageField(upload_to='pproductimg/')),
                ('rproduct_quantity', models.BigIntegerField(default=0)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep.Company')),
            ],
        ),
    ]
