# Generated by Django 2.0 on 2021-03-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep', '0006_auto_20210309_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comp_postalcode',
            field=models.BigIntegerField(),
        ),
    ]
