# Generated by Django 3.0 on 2021-03-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep', '0007_auto_20210313_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleorder',
            name='pickup_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
