# Generated by Django 2.0 on 2021-02-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep', '0007_recycleproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recycleproduct',
            name='rproduct_image',
            field=models.ImageField(upload_to='rproductimg/'),
        ),
    ]
