# Generated by Django 3.0 on 2021-03-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep', '0011_auto_20210329_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_placed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_qty',
            field=models.BigIntegerField(null=True),
        ),
    ]
