# Generated by Django 3.0 on 2021-03-29 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ep', '0013_auto_20210329_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_id',
        ),
    ]
