# Generated by Django 2.0 on 2021-01-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eplastic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plasticc',
            old_name='pc',
            new_name='pc_contact',
        ),
        migrations.RemoveField(
            model_name='master',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='plasticc',
            name='pc_address',
        ),
    ]
