# Generated by Django 2.0 on 2021-01-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eplastic', '0002_auto_20210105_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='otp',
            field=models.BigIntegerField(default=123),
        ),
    ]
